config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root "home#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
    before_save :capitalize_first_letter

  validates :name, presence: true
  validates :category, presence: true
  validates :priority, presence: true
  validates :status, presence: true

  private

  # Capitalizes the first letter of the task name
  def capitalize_first_letter
    self.name = self.name.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #used for home page 
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
    if params[:search].present?
      search_term = "%#{params[:search].downcase}%"
      @tasks = @tasks.where("LOWER(name) LIKE ?", search_term)
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    #used set_task method
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    #used set_task method
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :category, :priority, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'TaskManagement App', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
      <li class="nav-item">
        <%= link_to 'Tasks List', tasks_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add Task', new_task_path, class:"nav-link" %>
      </li>
      
    </ul>
    <%= form_with(url: tasks_path, method: :get, local: true, class: "form-inline my-2 my-lg-0") do %>
      <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Search", aria: { label: "Search" } %>
      <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/home/about.html.erb
<h1>about us </h1>

app/views/home/index.html.erb
<h1>Task Management App</h1>
  

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  
<%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
   <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">

    <title>TaskManagement App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

     <%= render 'home/header' %>
      <div class='container'>
      </br>
      <% if notice %>
      <%= render 'layouts/alert' %>
      <% end %>

         </br>
          <%= yield %>
      </div>

    
    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
   
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h4>
      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container mt-4">

    <!-- Task Name -->
    <div class="col-md-12 mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control", placeholder: "Task Name" %>
    </div>

    <!-- Category -->
    <div class="col-md-12 mb-3">
      <%= form.label :category, class: "form-label" %>
      <select name="task[category]" id="exampleFormControlSelect1" class="custom-select">
        <option value="" <%= 'selected' if task.category.blank? %>>Select Category</option>
        <option value="personal" <%= 'selected' if task.category == 'personal' %>>Personal</option>
        <option value="work" <%= 'selected' if task.category == 'work' %>>Work</option>
        <option value="shopping" <%= 'selected' if task.category == 'shopping' %>>Shopping</option>
      </select>
    </div>

    <!-- Priority -->
    <div class="col-md-12 mb-3">
      <%= form.label :priority, class: "form-label" %>
      <select name="task[priority]" id="exampleFormControlSelect2" class="custom-select">
        <option value="" <%= 'selected' if task.priority.blank? %>>Select Priority</option>
        <option value="High" <%= 'selected' if task.priority == 'High' %>>High</option>
        <option value="Medium" <%= 'selected' if task.priority == 'Medium' %>>Medium</option>
        <option value="Low" <%= 'selected' if task.priority == 'Low' %>>Low</option>
      </select>
    </div>

    <!-- Status -->
    <div class="col-md-12 mb-3">
      <%= form.label :status, class: "form-label" %>
      <select name="task[status]" id="exampleFormControlSelect3" class="custom-select">
        <option value="" <%= 'selected' if task.status.blank? %>>Select Status</option>
        <option value="complete" <%= 'selected' if task.status == 'complete' %>>Complete</option>
        <option value="incomplete" <%= 'selected' if task.status == 'incomplete' %>>Incomplete</option>
      </select>
    </div>

    <!-- Submit Button -->
    <div class="col-md-12 mb-3">
      <%= form.submit 'Save Task', class: "btn btn-secondary" %>
    </div>

  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <table>
    <tbody>
      <tr>
        <th>Name:</th>
        <td><%= task.name %></td>
      </tr>
      <tr>
        <th>Category:</th>
        <td><%= task.category %></td>
      </tr>
      <tr>
        <th>Priority:</th>
        <td><%= task.priority %></td>
      </tr>
      <tr>
        <th>Status:</th>
        <td><%= task.status %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/tasks/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2 text-center">
      <h1>Editing Task</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= render "form", task: @task %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-8 offset-md-2 text-center">
      <%= link_to "Show", @task, class: "btn btn-dark" %>
      <%= link_to "Back", tasks_path, class: "btn btn-dark" %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<% if @tasks.any? %>
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Task Name</th>
        <th>Category</th>
        <th>Priority</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.name, task_path(task) %></td>
          <td><%= task.category %></td>
          <td><%= task.priority %></td>
          <td><%= task.status %></td>
          <td>
            <%= link_to "Edit", edit_task_path(task), class: 'btn btn-outline-primary' %>
            <%= link_to "Delete", task_path(task), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No tasks found.</p>
<% end %>

<%= link_to "New Task", new_task_path, class: "btn btn-secondary" %>

<% unless @tasks.any? %>
  <h1>Hello world</h1>
  <p>This is the task app.</p>
<% end %>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2 text-center">
      <h1>Add New Task</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= render "form", task: @task %>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-md-8 offset-md-2 text-center">
      <%= link_to "Back to tasks", tasks_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @task.name %></h1>
  <p class="lead">
    <%= @task.category %> | <%= @task.priority %> | <%= @task.status %>
  </p>

  <!-- Flag for High Priority -->
  <% if @task.priority == "High" %>
    <div class="alert alert-danger" role="alert">
      <i class="fas fa-flag"></i> High Priority
    </div>
  <% elsif @task.priority == "Medium" %>
    <!-- Flag for Medium Priority -->
    <div class="alert alert-warning" role="alert">
      <i class="fas fa-flag"></i> Medium Priority
    </div>
  <% elsif @task.priority == "Low" %>
    <!-- Flag for Low Priority -->
    <div class="alert alert-success" role="alert">
      <i class="fas fa-flag"></i> Low Priority
    </div>
  <% end %>

 

  <%= link_to "Edit", edit_task_path(@task), class: "btn btn-secondary" %>
  <%= link_to "Back", tasks_path, class: "btn btn-secondary" %>
</div>